version: "3.8"

services:
  api:
    image: "node:alpine"
    working_dir: /app
    volumes:
      - /api/node_modules
      - ./api:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"
    depends_on:
      - db
  front:
    image: "node:alpine"
    working_dir: /app
    volumes:
      - /front/node_modules
      - ./front:/app
    ports:
      - "8080:5173"
    command: sh -c "npm install && npm run dev "
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"