version: "3"

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    depends_on:
      - db
  front:
    build: ./front
    volumes:
      - ./front:/app
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"