version: "3.8"

services:
  proxy:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "5173:5173"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  api:
    image: "node:alpine"
    working_dir: /app
    volumes:
      - /api/node_modules
      - ./api:/app
    expose:
      - "3000"
      - "5555"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db

  front:
    image: "node:alpine"
    working_dir: /app
    volumes:
      - /front/node_modules
      - ./front:/app
    expose:
      - "80"
    command: sh -c "npm install && npm run dev "
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    command: --replSet s0
    expose:
      - "27017"
    logging:
      driver: none